workflow_dir: "huabu_step3"    # huabu_refine01
workflow_name: "000"

available_models: 
- "default"
- "0.9.1"
# available_workflows:
# - 

api_mode: "v01"
api_model_name: "qwen2_72B" # used when set api_mode as llm
check_dependency: true
check_duplicate: true
max_duplicated_limit: 2
api_entity_linking: true

user_mode: "manual"
user_model_name: "qwen2_72B" # used when set user_mode as llm

model_name: "qwen2_72B" # "qwen2_72B"
template_fn: "query_PDL.jinja"
pdl_version: "v1"
pdl_extension: ".txt"
greeting_msg: "你好，我是{name}机器人，有什么可以帮您?"

