workflow_dir: "pdl2_0729"    # huabu_refine01
workflow_name: "000"

available_models: 

api_mode: "v01"
api_model_name: "qwen2_72B" # used when set api_mode as llm

user_mode: "manual"
user_model_name: "qwen2_72B" # used when set user_mode as llm

model_name: "qwen2_72B" # "qwen2_72B"
template_fn: "query_PDL.jinja"
pdl_version: "v2"
pdl_extension: ".yaml"
greeting_msg: "Hi, I's a bot for {name}. How can I help you?"

