# https://docs.streamlit.io/develop/api-reference/configuration/config.toml
[theme]
layout = "wide"
primaryColor = "#FFA500"  # 橙色
backgroundColor = "#FFF5E6"  # 非常浅的橙色
secondaryBackgroundColor = "#FFE5B4"  # 浅橙色
textColor = "#000000"  # Black
font = "serif"  # "sans serif"

[browser]
gatherUsageStats = false

[server]
port = 18801
runOnSave = true
fileWatcherType = "auto"  # watchdog