conversation_turn_limit: 10

workflow_id: "000"
workflow_type: "text"

user_mode: "input_user"   # dummy_user

bot_mode: "react_bot"     # dummy_bot
bot_template_fn: "baselines/flowbench.jinja"
bot_llm_name: "gpt-4o"
bot_action_limit: 5

api_mode: "llm"
api_template_fn: "baselines/api_llm.jinja"
api_llm_name: "gpt-4o"

