# Full configs for non-UI usage
defaults: !include default.yaml

# workflow_dataset: "v241127_converted_ruled"
workflow_dataset: "v241127"
workflow_id: "000"       # 挂号

bot_llm_name: "test-eason"
bot_template_fn: "bot_pdl_ui_zh.jinja"
bot_retry_limit: 3
bot_action_limit: 10
ui_greeting_msg: "你好，我是 {name} 机器人，有什么可以帮您?"
api_entity_linking: false               # entity linking! FIXME: entity linker message not in log! (mismatch with client)
bot_pdl_controllers:
  - {name: "api_duplication", config: {if_pre: true, if_post: true, threshold: 2}, is_activated: true}
  - {name: "node_dependency", config: {if_pre: false, if_post: true}, is_activated: true}
  # - {name: "session_length", config: {if_pre: true, min: 5, max: 15}, is_activated: true}

db_uri: "mongodb://9.134.230.111:27017/"
db_name: "agent-pdl"
db_collection_single: "dev_single_sessions"
db_collection_multi: "dev_multi_sessions"
exp_version: "cli_241224"     # NOTE: to set the exp_version!

backend_url: "http://localhost:8101"
