# FC mode!
defaults: !include default.yaml

ui_bot_mode: ui_single_bot
ui_default_model: "gpt-4o-mini"
ui_default_template: "bot_pdl_ui_zh_fc.jinja"
ui_bot_template_fn: "flowagent/bot_pdl_ui_zh_fc.jinja"
ui_greeting_msg: "你好，我是{name}机器人，有什么可以帮您?"

api_entity_linking: false               # turn off entity linking!

bot_pdl_controllers:
  - {name: "api_duplication", config: {if_pre: true, if_post: true, threshold: 2}, is_activated: true}
  - {name: "node_dependency", config: {if_pre: true, if_post: true}, is_activated: true}
  # - {name: "session_length", config: {if_pre: true, min: 5, max: 15}, is_activated: true}

db_uri: "mongodb://9.134.230.111:27017/"
db_name: "agent-pdl"
db_collection_single: "exp_fc_single_sessions"
db_collection_multi: "exp_fc_multi_sessions"

backend_url: "http://localhost:8101"
