# ================================= update @240827
workflow_dir: "pdl"        # 
workflow_name: "000"

available_models: 
# - "default"
# - "0.9.1"
# available_workflows:
# - 

api_mode: "v01"                 # manual, v01, llm
api_model_name: "gpt-4o"        # used when set api_mode as llm
fn_api_infos: "api_v02/api_infos.json"
check_dependency: true          # 
check_duplicate: true           # 
max_duplicated_limit: 2         # 
api_entity_linking: true        # bool, whether 

user_mode: "manual"
user_model_name: "gpt-4o"       # used when set user_mode as llm

bot_mode: "pdl"                   # pdl, lke
model_name: "gpt-4o"            # "gpt-4o"
template_fn: "query_PDL.jinja"
greeting_msg: "你好，我是 {name} 机器人，有什么可以帮您?"

