# ================================= update @240821
workflow_dir: "pdl_v0828"      # huabu_refine01
workflow_name: "000-114挂号"

available_models: 
- "default"
- "0.9.1"
available_workflow_dirs:
- "pdl2_step3"
- "pdl_v0828"
available_workflows:
# - '000-114挂号'
# - "002-新闻查询"
# - '019-礼金礼卡类案件'
# - '023-查号源日期'
# - '025-酒店取消订单'
# - 003-物品能否邮寄
# - 005-课程调整
# - 006-同程开发票
# - 007-门诊费用报销
# - 008-寄快递
# - 012-就诊预约咨询
- 000-114挂号
- 002-新闻查询
- 003-物品能否邮寄
- 004-服务网点查询
- 006-同程开发票
- 007-门诊费用报销

available_templates:
- query_PDL.jinja
default_model: default

api_mode: "v01"
# api_model_name: "gpt-4o"
check_dependency: true
check_duplicate: true
max_duplicated_limit: 2
api_entity_linking: true

user_mode: "manual"
# user_model_name: "gpt-4o"

model_name: "qwen2_72B"         # "qwen2_72B"
template_fn: "query_PDL.jinja"
greeting_msg: "你好，我是{name}机器人，有什么可以帮您?"


