# ================================= update @240821
workflow_dir: "pdl2_step3"    # huabu_refine01
workflow_name: "000-114挂号"

available_models: 
- "default"
- "0.9.1"

api_mode: "v01"
# api_model_name: "gpt-4o"
check_dependency: true
check_duplicate: true
max_duplicated_limit: 2
api_entity_linking: true

user_mode: "manual"
# user_model_name: "gpt-4o"

model_name: "qwen2_72B" # "qwen2_72B"
template_fn: "query_PDL.jinja"
greeting_msg: "你好，我是{name}机器人，有什么可以帮您?"


