# ================================= update @240820
workflow_dir: "pdl"        # 
workflow_name: "000"

available_models: 
- gpt-4o
- custom
- "default"
- "0.9.1"
available_workflow_dirs:
- "pdl"
available_workflows:
# - '000-114挂号'
# - "002-新闻查询"
# - '019-礼金礼卡类案件'
# - '023-查号源日期'
# - '025-酒店取消订单'
available_templates:
- query_PDL.jinja
default_model: gpt-4o

api_mode: "llm"                 # manual, v01, llm
api_model_name: "gpt-4o"        # used when set api_mode as llm
check_dependency: true          # 
check_duplicate: true           # 
max_duplicated_limit: 2         # 
api_entity_linking: true        # bool, whether 

user_mode: "manual"
user_model_name: "gpt-4o"       # used when set user_mode as llm

model_name: "gpt-4o"            # "gpt-4o"
template_fn: "query_PDL.jinja"
greeting_msg: "你好，我是{name}机器人，有什么可以帮您?"

