
ui_available_models:
  - "1.0.2"
  - "default"
  - "gpt-4o-mini"
  - "gpt-4o"
  - Vendor-A/Qwen/Qwen2.5-72B-Instruct
  - Qwen/Qwen2.5-7B-Instruct
  - Qwen2.5-72B-INT8
  - "debug"
ui_available_templates:
  # - bot_pdl.jinja
  - bot_pdl_ui.jinja
  - bot_pdl_ui_zh.jinja
# ui_available_workflow_dirs:
# ui_available_workflows:
ui_default_model: "default"   # "gpt-4o"
ui_default_template: "bot_pdl_ui_zh.jinja"
ui_bot_template_fn: "flowagent/bot_pdl_ui_zh.jinja"
ui_greeting_msg: "你好，我是{name}机器人，有什么可以帮您?"
ui_available_workflow_datasets:
  - "v241127"
  - "PDL_zh"
ui_default_workflow_dataset: "v241127"
ui_tools:
  - {name: web_search, is_enabled: false}
  - {name: hunyuan_search, is_enabled: true}

# mui_available_workflows:
#   - 114挂号
#   - 新闻查询
mui_agent_main_template_fn: "flowagent/bot_mui_main_agent.jinja"
mui_agent_main_llm_name: "gpt-4o"
mui_agent_workflow_template_fn: "flowagent/bot_mui_workflow_agent.jinja"
mui_available_models:
  - "1.0.2"
  - "default"
  - "gpt-4o-mini"
  - "gpt-4o"
  - Vendor-A/Qwen/Qwen2.5-72B-Instruct
  - Qwen/Qwen2.5-7B-Instruct
  - Qwen2.5-72B-INT8
  - "debug"
mui_agent_main_available_templates:
  - bot_mui_main_agent.jinja
mui_agent_workflow_available_templates:
  - bot_mui_workflow_agent.jinja
mui_agent_main_default_template: "bot_mui_main_agent.jinja"
mui_agent_workflow_default_template: "bot_mui_workflow_agent.jinja"
mui_agent_main_default_model: "default"
mui_default_workflow_dataset: "v241127"
mui_greeting_msg: "你好，有什么可以帮您?"

pdl_version: "pdl"    # set as default


# NOTE: the following 5 fields identify one experiment!!!
# specifically, workflow_dataset & workflow_type should be all same for one exp_version
# i.e. one `exp_version + workflow_id` identify one experiment
workflow_dataset: "v241127" # "v241127"  # "PDL_zh"
workflow_type: "pdl"       # text, code, flowchart, pdl, core
workflow_id: "000"
exp_version: "default"
exp_mode: "session"        # session, turn
exp_save_config: false
exp_check_if_run: false    # DONOT check this experiment if it has been run if set as false!

user_mode: "input_user"   # dummy_user, input_user, llm_profile, llm_oow
user_llm_name: "gpt-4o-mini"
user_template_fn: null    # "flowagent/user_llm.jinja"
# user_profile: true      # -> exp_mode
user_profile_id: 0
user_oow_ratio: 0.2

bot_mode: "pdl_bot"       # dummy_bot, react_bot, pdl_bot, core_bot
bot_template_fn: null     # "flowagent/bot_flowbench.jinja"
bot_llm_name: "gpt-4o"
bot_action_limit: 5
bot_pdl_controllers:
  - {name: "api_duplication", config: {if_pre: true, if_post: true, threshold: 2}, is_activated: true}
  - {name: "node_dependency", config: {if_pre: true, if_post: true}, is_activated: true}
  # - {name: "session_length", config: {if_pre: true, min: 5, max: 15}, is_activated: true}


api_mode: "request"           # dummy_api, llm, core, request
api_template_fn: null         # "flowagent/api_llm.jinja"
api_llm_name: "gpt-4o-mini"
api_entity_linking: true
api_entity_linking_llm: "gpt-4o"
api_entity_linking_template: "flowagent/entity_linking.jinja"

conversation_turn_limit: 20
log_utterence_time: false
log_to_db: true

db_uri: 'mongodb://localhost:27017'
db_name: "agent-pdl"
# db_message_collection_name: "messages"
# db_meta_collection_name: "config"

backend_url: "http://localhost:8101"

# simulate_num_persona: 5
# simulate_max_workers: 10

# judge_max_workers: 10
# judge_model_name: "gpt-4o"
# judge_conversation_id: "2024-09-19 15:20:53.462895"
# judge_log_to: "wandb"
# judge_force_rejudge: false
